---
  - name: Install Epel Repo 
    yum:
      name: 
        - epel-release
      state: present
  - name: Install Packages
    dnf:
      name: 
        - iptables-services
        - git
        - mlocate
        - wget
        - vim
        - net-tools
        - htop
        - python3
        - lvm2
        - btop
      state: present

