---
- hosts: Centos7
  tasks:
    - name: Install Epel Repo 
      yum:
        name: 
          - epel-release
        state: present
    - name: Install Packages
      yum:
        name: 
          - iptables-services
          - git
          - mlocate
          - wget
          - vim
        state: present