- hosts: Proxmox
  tasks:
  - name: Comment Ceph PVE Subscription repos
    replace:
       path: /etc/apt/sources.list.d/ceph.list
       regexp: 'deb'
       replace: '#deb'

  - name: Comment PVE Subscription repos
    replace:
       path: /etc/apt/sources.list.d/pve-enterprise.list
       regexp: 'deb'
       replace: '#deb'

  - name: "Create file for Non Subscription PVE repo"
    copy:
      dest: "/etc/apt/sources.list.d/pve-non-subscription.list"
      content: |
        deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

  - name: Update cache
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 
  
  - name: Install system packages
    apt:
      name: 
        - git
        - telnet
        - neovim
        - neofetch
        - htop
      state: present
   
  - name: Install docker
    apt:
      name: docker.io
      state: present

  - name: Add portainer container
    docker_container:
      name: portainer
      image: portainer/portainer-ce
      restart_policy: unless-stopped
      ports:
        - "8000:8000"
        - "9000:9000"
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      state: started
      recreate: yes

  - name: Install oh my zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      creates: /root/.oh-my-zsh

  - name: Change oh my zsh theme
    replace:
      path: /root/.zshrc
      regexp: 'ZSH_THEME="robbyrussell"'
      replace: 'ZSH_THEME="agnoster"'  
  
  - name: Add alias to zshrc
    lineinfile:
      path: /root/.zshrc
      line: "alias vim='nvim'"
      state: present
      create: yes
      insertafter: "plugins=(git)"
      backup: yes

  
  
