- hosts: 127.0.0.1
  connection: local
  gather_facts: no


  tasks:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - VMs/*.yml

    - include_tasks: "{{ item }}"
      with_fileglob:
        - LXC/*.
