- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    - proxmoxIP: vm2.ggmartinez.duckdns.org
    - proxmoxUser: root@pam
    - proxmoxPassword: maiden
    - proxmoxNode: vm2
    - proxmoxCentosTemplate: Centos7
  tasks:
    - name: Create Rancher VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmoxUser }}"
        api_password: "{{ proxmoxPassword }}"
        api_host: "{{ proxmoxIP }}"
        clone: "{{ proxmoxCentosTemplate }}"
        name: K8s---Rancher
        node: vm2
        proxmox_default_behavior: "no_defaults"
        full: no
        cores: 2
        memory: 2048
        nameservers: "192.168.1.254"
        searchdomains: "ggmartinez.duckdns.org"
        ipconfig:
          ipconfig0: 'ip=192.168.1.50/24,gw=192.168.1.1'
        virtio:
          virtio0: 'local-lvm:10'
          virtio1: 'local-lvm:10'
        update: true
      