---
- hosts: Rancher
  tasks:

    - name: Add Rancher Helm repository
      kubernetes.core.helm_repository:
        name: rancher-latest
        repo_url: https://releases.rancher.com/server-charts/latest



    - name: Install Cert Manager CRDS
      kubernetes.core.k8s:
        state: present
        src: https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml


    - name: Add Cert Manager Helm repository
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io


    - name: Install Cert Manager via Helm
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        chart_version: v1.5.1
        kubeconfig: /etc/rancher/k3s/k3s.yaml


    - name: Create Rancher Namespace in K8s
      k8s:
        name: cattle-system
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml




    - name : Install Rancher via Helm
      kubernetes.core.helm:
        name: rancher
        chart_ref: rancher-latest/rancher
        release_namespace: cattle-system
        values:
          replicas: 3
          hostname: rancher.ggmartinez.duckdns.org
          ingress:
            tls:
              source: rancher
        kubeconfig: /etc/rancher/k3s/k3s.yaml


  become: true
  become_user: root
