---
  - name: Install Epel Repo 
    yum:
      name: 
        - epel-release
      state: present
  - name: Install Packages
    yum:
      name: 
        - iptables-services
        - git
        - mlocate
        - wget
        - vim
        - net-tools
        - htop
        - ntp
        - ntpdate
        - libselinux-python 
        - python3
        - lvm2
      state: present

