---
  - name: Install Prometheus Exporter 
    yum:
      name: 
        - golang-github-prometheus-node-exporter
      state: present

  - name: Enable Prometheus Node Exporter
    systemd:
      state: started
      enabled: yes
      name: node_exporter
