---
- hosts: K8s
  tasks:

  - include_tasks: ../Common/K3s/Install.yml
    tags: InstallK3s

  - name: Copy Manifests to Server
    copy: 
      src: Manifests
      dest: /tmp

  - name: Create Admin Account
    shell: "/usr/local/bin/kubectl apply -f /tmp/Manifests/AdminAccount.yml"

  - name: Create LetsEncrpyt Cert Manager
    shell: "/usr/local/bin/kubectl apply -f /tmp/Manifests/LetsEncryptCertManager.yml"
  
  - name: Wait for Cert Manager to start up
    shell: sleep 120
    changed_when: False

  - name: Create LetsEncrpyt Issuer
    shell: "/usr/local/bin/kubectl apply -f /tmp/Manifests/LetsEncryptIssuer.yml"

  become: yes
  become_user: root