---
- hosts: Centos7
  tasks:
    - name: Install Epel Repo 
      yum:
        name: 
          - epel-release
        state: present
    - name: Install Packages
      yum:
        name: 
          - iptables-services
          - git
          - mlocate
          - wget
          - vim
          - net-tools
          - htop
          - ntp
          - ntpdate
          - libselinux-python 
          - golang-github-prometheus-node-exporter
        state: present
        
    - name: Install or update pip
      community.general.easy_install:
        name: pip
        state: latest

    - name: Set timezone
      timezone:
        name: America/Montevideo

    - name: Start ntpd service
      systemd:
        state: started
        enabled: yes
        name: ntpd

    - name: Turn off SELinux
      selinux:
        state: disabled

    - name: Disable SELinux
      selinux:
        policy: targeted
        state: permissive

  become: yes
  become_user: root