---
- hosts: Centos7
  tasks:
    - name: Set Hostname
      hostname:
        name: "{{ inventory_hostname }}"
        state: present
        
    - name: Install Epel Repo 
      yum:
        name: 
          - epel-release
        state: present
    - name: Install Packages
      yum:
        name: 
          - iptables-services
          - git
          - mlocate
          - wget
          - vim
          - net-tools
          - htop
          - ntp
          - ntpdate
          - libselinux-python 
          - golang-github-prometheus-node-exporter
          - python-pip
        state: present

    - name: Set timezone
      timezone:
        name: America/Montevideo

    - name: Start ntpd service
      systemd:
        state: started
        enabled: yes
        name: ntpd

    - name: Turn off SELinux
      selinux:
        state: disabled

    - name: Disable SELinux
      selinux:
        policy: targeted
        state: permissive
    
    - name: Enable Prometheus Node Exporter
      systemd:
        state: started
        enabled: yes
        name: node_exporter

  become: yes
  become_user: root